name: Validar grupos

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  validar:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Instalar uv
        uses: astral-sh/setup-uv@v5

      - name: Instalar Python
        run: uv python install

      - name: Instalar dependencias
        run: uv sync --locked

      - name: Validar archivos YAML
        run: uv run python scripts/validar.py
